---
aws_access_key: "Enter your Key ID"
aws_secret_key: "Enter your secret"
region: "us-east-2"

# VPC
vpc_cidr: 10.10.0.0/24
vpc_name: "Ansible VPC3"

# Subnet
subnet_name: "Ansible Subnet"
subnet_cidr: 10.10.0.0/26

igw_name: "Traffic IGW"


#route table name
route_name: "Public Ansible"

securitygroup_name: "Ansible Security Group"

ec2_tag: "WebServer"


#key storage location
ec2_key_directory: "/etc/ansible/aws"
keypair_name: "ansible_key"

